### ISSUE TITLE
Enable Pipelining throws error

### ISSUE THREAD

**Issue by mjm2312** [danitseitlin/redis-modules-sdk-ts#214]
When I set enableAutoPipelining: true, I get this error:

```
packages/time-series/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:705:11)
    at Command.toWritable (packages/time-series/node_modules/redis-modules-sdk/node_modules/ioredis/built/command.js:163:20)
    at Redis.sendCommand (packages/time-series/node_modules/redis-modules-sdk/node_modules/ioredis/built/redis/index.js:664:47)
    at packages/time-series/node_modules/redis-modules-sdk/node_modules/ioredis/built/redis/event_handler.js:273:22
    at packages/time-series/node_modules/redis-modules-sdk/node_modules/ioredis/built/redis/event_handler.js:70:51
    at packages/time-series/node_modules/redis-modules-sdk/node_modules/ioredis/built/redis/index.js:494:13
    at tryCatcher (packages/time-series/node_modules/standard-as-callback/built/utils.js:12:23)
    at packages/time-series/node_modules/standard-as-callback/built/index.js:22:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```
sample code:
import { RTS } from 'redis-modules-sdk';
```

const test = async () => {
  try {
    const client = new RTS({
      host: 'localhost',
      port: 6381,
      enableAutoPipelining: true,
    });
    await client.connect();
    const res = await client.queryindex('id=asdf');
    await client.disconnect();
    console.log('end of test');
  } catch (e) {
    console.log('caught error, ', e);
  }
};

test();

```
Would you be able to investigate this issue? Thank you

**Comment by danitseitlin** [comment]
@mjm2312 Thanks, will take a look ASAP

**Comment by danitseitlin** [comment]
@mjm2312 Seems like the ioredis pkg was outdated, updated it now and it should support `enableAutoPipelining` feature.
Let me know if it doesn't.
Have a good one ✌🏼
